### ISSUE TITLE
WASM compilation

### ISSUE THREAD

**Issue by olanod** [timokoesters/conduit#2]
The go folks were experimenting with a libp2p based version of Dendrite a while back that compiled to WASM and ran in the browser. It might not be a goal of Conduit now or anytime in the close future but it would be definitely a nice to have functionality that I believe fits better in a Rust based home server that can be lighter and more performant than the go version. 

This issue can be for tracking and discussing the long term changes that would make Conduit suitable for running in a browser.

**Comment by timokoesters** [comment]
This repo is just a mirror. See https://gitlab.com/famedly/conduit/-/issues/38

**Comment by olanod** [comment]
My bad, wrong place https://git.koesters.xyz/timo/conduit/issues/240
